### ISSUE TITLE
Investigate too high staking rewards amounts

### ISSUE THREAD

**Issue by pocin** [TempleDAO/temple-price-bot#3]
logs show 
```
19|temple- | Refreshing price
19|temple- | New stats T $0.77 | OG $2.33 || Rwrds $2K | Stkd 86%
19|temple- | Refreshing price
19|temple- | New stats T $0.77 | OG $2.33 || Rwrds $156K | Stkd 86%
```
and we got user reports that the amount was high https://discord.com/channels/847178511604252741/900905463309303899/945477845243789332 as well

@gg-salo do you have bandwidth to
1) change logging from `print()` to built in `logging` or (preferably) https://loguru.readthedocs.io/en/stable/overview.html so we get more details in logs (especially utc timestamp)
2) get the historical graph data (for past 2 days or so) and run it through the bot formatting functions if the bug is not in the `milify()`? This might require some refactoring so do not hesitate to do that. Might be good idea to add some unit tests at this point.

@medariox suggested this could be a bug in substracting the data from previous day (so it would show total accumulated instead of the diff).

or try to debug it?

**Comment by medariox** [comment]
Fixed with https://github.com/TempleDAO/temple-price-bot/pull/5
